#!/bin/bash
#SBATCH -J sim2m_rareCov_test5_n8h
#SBATCH -N 1 -c 6
#SBATCH --mem=12G
#SBATCH -o record/slurm_%j_%x_log.out
#SBATCH -e record/slurm_%j_%x_err.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=z.h.wu@link.cuhk.edu.hk
#SBATCH --array=1-3

# basic information
echo Time is `date`
echo Job name: $SLURM_JOB_NAME 

# activate conda environment
source ~/.bashrc
conda activate py_ddml

# set working directory
cd /project/Stat/s1155168529/programs/DDML

# default value
alpha=5
beta=2

## set variable parameters
d_candi=(0 1 2)
idx=$((SLURM_ARRAY_TASK_ID - 1))
d_curr=${d_candi[idx]}
# d_curr_tag=$(echo "$d_curr * 10" | bc | cut -d. -f1)

# print info
echo ======================================
echo Time is `date`
echo Job name: $SLURM_JOB_NAME with d_curr = $d_curr
echo Running on the node: $SLURM_JOB_NODELIST

# main part
srun python code/simulation/sim2m_rareCov_test5.py \
    --n_rnp=500 \
    --n_rds=5 \
    --n=800 \
    --n_rft=100 \
    --p=10 \
    --den_est="single" \
    --K=5 \
    --mu_alpha=${alpha} \
    --mu_beta=${beta} \
    --mu_ip=${d_curr} \
    --path_out="output/out_sim2m_t5_rareCov_n8h_alpha${alpha}_beta${beta}_ip${d_curr}.csv"
