#!/bin/bash
#SBATCH -J sim2b_test3
#SBATCH -N 1 -c 5
#SBATCH --mem=12G
#SBATCH -o record/slurm_%j_%x_log.out
#SBATCH -e record/slurm_%j_%x_err.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=z.h.wu@link.cuhk.edu.hk
#SBATCH --array=1-3

# basic information
echo Time is `date`
echo Job name: $SLURM_JOB_NAME 

# activate conda environment
source ~/.bashrc
conda activate py_ddml

# set working directory
cd /project/Stat/s1155168529/programs/DDML

# default value

## set variable parameters
p_candi=(0.05 0.20 0.50)
idx=$((SLURM_ARRAY_TASK_ID - 1))
p_curr=${p_candi[idx]}
p_curr_tag=${p_curr//./}

# print info
echo ======================================
echo Time is `date`
echo Job name: $SLURM_JOB_NAME with d_curr = $d_curr
echo Running on the node: $SLURM_JOB_NODELIST

# main part
srun python code/simulation/sim2b_rareCov_test3.py \
    --n_rnp=500 \
    --n_rds=5 \
    --n=500 \
    --n_rft=100 \
    --p=3 \
    --den_est="single" \
    --prob_d=${p_curr} \
    --K=5 \
    --path_out="output/out_sim2b_t3_p${p_curr_tag}.csv"
