#!/bin/bash
#SBATCH -J sim2mc_test7_vgams7_ub
#SBATCH -N 1 -c 5
#SBATCH --mem=12G
#SBATCH -o record/slurm_%j_%x_log.out
#SBATCH -e record/slurm_%j_%x_err.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=z.h.wu@link.cuhk.edu.hk
#SBATCH --array=1-4

# basic information
echo Time is `date`
echo Job name: $SLURM_JOB_NAME 

# activate conda environment
source ~/.bashrc
conda activate py_ddml

# set working directory
cd /project/Stat/s1155168529/programs/DDML

# default value
beta=2.0
vgam=7

## set variable parameters
d_candi=(1 2 1 2)
vss_candi=(1 1 2 2)

idx=$((SLURM_ARRAY_TASK_ID - 1))

d_curr=${d_candi[idx]}
d_curr_tag=$(echo "$d_curr * 10" | bc | cut -d. -f1)

vss_curr=${vss_candi[idx]}

# print info
echo ======================================
echo Time is `date`
echo Job name: $SLURM_JOB_NAME with d_curr = $d_curr and vss_curr = $vss_curr
echo Running on the node: $SLURM_JOB_NODELIST

# main part
srun python code/simulation/sim2m_rareCov_test7_vgam_vss.py \
    --n_rnp=2000 \
    --n_rds=5 \
    --n_rft=100 \
    --n=400 \
    --p=5 \
    --den_est="double" \
    --K=10 \
    --vgam=${vgam} \
    --mu_beta=${beta} \
    --mu_ip=${d_curr} \
    --vss=${vss_curr} \
    --path_out="output/out_sim2mc_ub_t7_vgams${vgam}_vss${vss_curr}_beta${beta}_ip${d_curr_tag}.csv"
